version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=example
      - DB_NAME=logs_amqp
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=logs_amqp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # Port standard RabbitMQ
      - "15672:15672" # Port de management RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Port de l'interface web MailHog
      - "1025:1025" # Port SMTP MailHog

volumes:
  db_data:
  rabbitmq_data:
